[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "boum"
version = "1.2.3"
description = "SDK to interact with the boum API"
authors = ["Marc Pfander <marc.pfander@boum.garden>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/boum-garden/sdk"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
pylint = "^2.15.6"
bumpver = "^2022.1119"
pytest-rerunfailures = "^10.3"
pandas = "^1.5.2"
bandit = "^1.7.4"
coverage = "^6.5.0"
pytest-cov = "^4.0.0"
pytest-xdist = "^3.1.0"
regex = "^2023.6.3"

[tool.bumpver]
current_version = "1.2.3"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = false
push = false

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'current_version = "{version}"',
    'version = "{version}"',
]

[tool.bandit]
skips = ["B101", "B311"]


