[tool.poetry]
name = "news-toolkit-api"
version = "0.0.5"
description = ""
authors = ["wakita181009 <wakita181009@gmail.com>"]
readme = "README.md"
packages = [{ include = "news_toolkit_api" }]

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
fastapi = "^0.100.1"
fastapi-injector = "^0.5.1"
google-cloud-ndb = "^2.2.0"
uvicorn = { extras = ["standard"], version = "^0.23.2" }
aiohttp = "^3.8.5"
beautifulsoup4 = "^4.12.2"


[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
flake8 = "^6.1.0"
flake8-pyproject = "^1.2.3"
mypy = "^1.4.1"
isort = "^5.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
