[tool.poetry]
name = "jamofetch"
version = "3.7.2"
description = "A thin wrapper to retrieve sequence from JAMO at NERSC and on Dori."
authors = ["Duncan Scott"]
license = "None"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8"

[tool.poetry.dev-dependencies]

[tool.poetry.group.dev.dependencies]
sphinx-autoapi = "^2.1.1"
sphinx-rtd-theme = "^1.2.2"

[tool.poetry.scripts]
jamofetch = 'jamofetch.jamofetch:cli'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
