[tool.poetry]
name = "pystasis"
version = "0.0.2"
description = "Detect breaking changes in Python projects"
authors = ["Regan Koopmans <regan@koopmans.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
git-python = "^1.0.3"
click = "^8.1.6"

[tool.poetry.scripts]
pystasis = "pystasis.cli:main"

[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
isort = "^5.12.0"
flake8 = "^6.0.0"

[tool.black]
line-length = 79


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
