[tool.poetry]
name = "pydantic-db-backend"
version = "0.9.0"
description = ""
authors = ["Marco Bartel <bsimpson888@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
python-dotenv = "^0.15.0"
couchdb = { version = "^1.2", optional = true }
pymongo = { version = "^3.13.0", optional = true }
pydash = "*"
iso8601 = "^1.1.0"
pydantic = "^1.10.7"
webexception = "^1.0.4"
pydantic-db-backend-common = "^1.0.1"


[tool.poetry.group.dev.dependencies]
coverage = "^7.2.7"
pytest = "^7.3.1"
freezegun = "^1.2.2"
couchdb = "^1.2"
pymongo = "^3.13.0"
pytest-mock = "^3.10.0"


[tool.poetry.extras]
couchdb = ["couchdb"]
mongodb = ["pymongo"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q -s -v"
testpaths = [
    "tests",
]
log_cli = true
log_cli_level = "debug"
#log_cli_format = "[%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_format = "[%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
