[project]
name = "simpleworkspace"
version = "1.1.229"
description = "Package created for https://spacerival.com, opensource and free to use and modify"
requires-python = ">=3.10"

[build-system]
requires = [ "setuptools",]
build-backend = "setuptools.build_meta"
