[tool.poetry]
name = "mlflow-knative"
version = "0.4.3"
description = "MLflow plugin adding a Knative deployment target"
authors = ["Loris Zinsou <lzinsou@protonmail.com>"]
readme = "README.md"
keywords = ["mlflow", "plugin", "mlops", "deployment", "deployments", "knative", "kubernetes", "kn", "k8s"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Plugins",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11"
]
repository = "https://gitlab.com/lzinsou/mlflow-knative"
packages = [{include = "mlflow_knative"}]

[tool.poetry.plugins."mlflow.deployments"]
knative = "mlflow_knative.deployment_client"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
kubernetes = "^26.1.0"
docker = "^6.1.3"
pyyaml = "^6.0"
types-pyyaml = "^6.0.12.10"

[tool.poetry.group.dev.dependencies]
mlflow = "~2"
flake8 = "^6.0.0"
mypy = "^1.2.0"
isort = "^5.12.0"
black = "^23.3.0"
pytest = "^7.3.1"
pytest-cov = "^4.0.0"

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "DEBUG"
log_cli_format = "%(asctime)s %(levelname)s %(message)s"

[tool.isort]
profile = "black"

[tool.mypy]
exclude = "tests"

[[tool.mypy.overrides]]
module = "mlflow.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "kubernetes.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "docker"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "requests.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "pandas.*"
ignore_missing_imports = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
