[build-system]
requires = [
    "setuptools>=61.0",
    "beautifulsoup4>=4.12.2",
    "lxml>=4.9.3",
    "requests==2.31.0",
    "pandas==2.0.3",
    "pathlib==1.0.1",
    "chromedriver-binary-auto>=0.3.0",
    "selenium==4.10.0",
    "selenium-wire==5.1.0",
    "tqdm==4.65.0"
]
build-backend = "setuptools.build_meta"

[project]
name = "creepypasta"
version = "0.0.5"
authors = [
  { name="Stephanie Andrews", email="jellomoat@gmail.com" },
]
description = "A small package to crawl CreepyPasta and parse into structured data."

readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[options.entry_points]
# console_scripts = 

[project.urls]
"Homepage" = "https://github.com/jellomoat/pasta"
"Bug Tracker" = "https://github.com/jellomoat/pasta/issues"
