[tool.poetry]
name = "ldimbenchmark"
version = "0.2.67"
description = ""
authors = ["DanielHabenicht <daniel-habenicht@outlook.de>"]
readme = "README.md"
exclude = [
    "tests",
    "experiments"
]

[tool.poetry.scripts]
ldimbenchmark = "ldimbenchmark.cli:cli"

[tool.poetry.dependencies]
python = ">=3.8,<4"
wntr = "^0.5.0"
pyyaml = "^6.0"
scikit-learn = "^1.1.3"
docker = "^6.0.1"
tabulate = "^0.9.0"
pydantic = "^1.10.2"
click = "^8.1.3"
pandas = "^1.5.2"
jinja2 = "^3.1.2"
numpy = "^1.23.5"
paramiko = "^3.0.0"
enlighten = "^1.11.2"
python-semantic-release = "^7.33.2"
sqlalchemy = "<2"
sympy = "^1.11.1"
more-itertools = "^9.1.0"
seaborn = "^0.12.2"
# This is needed because of https://github.com/pberkes/big_O/issues/46
big-o-latest = "^0.10.3"
tables = "^3.8.0"

[tool.poetry.group.dev.dependencies]
tox = "^3.27.1"
black = "23.1.0"
pytest = "7.2.1"
syrupy = "3.0.6"
pytest-xdist = "3.2.0"
pytest-benchmark = "4.0.0"
pyright = "^1.1.293"
pytest-testmon = { version = "^1.4.5", python = "<3.12" }
pytest-watch = "^4.2.0"

[tool.poetry.group.ci.dependencies]
tox-gh-actions = "^2.11.0"


[tool.poetry.group.docs.dependencies]
mkdocs-material = "^8.5.11"
mkdocstrings = {extras = ["python"], version = "^0.19.0"}
mkdocs-gen-files = "^0.4.0"
mkdocs-literate-nav = "^0.5.0"
mkdocs-section-index = "^0.3.4"
mkdocs-jupyter = "^0.22.0"
ipykernel = "^6.19.2"
mkdocs-git-revision-date-localized-plugin = "^1.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.semantic_release]
version_toml = [ "pyproject.toml:tool.poetry.version" ]
version_source = "tag"
branch = "main"
upload_to_release = true
upload_to_repository = true
build_command = "poetry build"

[tool.pytest.ini_options]
testpaths = ["tests"]
norecursedirs="test_data .ldim_benchmark_cache benchmark-results dist"
markers = ["noci: tests that should not run in ci."]

[tool.tox]
legacy_tox_ini = """
[tox]
isolated_build = True
envlist = py38,py39,py310

[gh-actions]
python =
    3.8: py38
    3.9: py39
    3.10: py310

[testenv]
deps =
    black==23.1.0
    pytest==7.2.1
    syrupy==3.0.6
    pytest-xdist==3.2.0
    pytest-benchmark==4.0.0
commands =
    black --check src/ldimbenchmark
    pytest -m "not noci"
"""

[tool.pyright]
include = ["src", "tests"]
exclude = ["**/node_modules", "**/__pycache__", "**/.ldim_benchmark_cache", "**/test_data"]
defineConstant = { DEBUG = true }

reportMissingImports = true
reportMissingTypeStubs = false
