[tool.poetry]
name = "barcodes-uc"
version = "0.6.1"
description = "A library to generate barcodes"
authors = ["Pedro Juan Royo <pedro.juan.royo@gmail.com>"]
readme = "README.md"
packages = [{include = "barcodes_uc"}]
include = ["data/*","requirements.txt"]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.25.1"
pandas = "^2.0.3"
pillow = "^10.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
