[project]
name = "data_ecosystem_flask"
authors = [{name="John Bowyer", email="zfi4@cdc.gov" }]
description = "Data Ecosystem Flask (PADE)  - Python "
readme = "readme.md"
requires-python = ">=3.9,<4.0"
version = "202307.0.12"
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.9"
]


[project.urls]
"Homepage" = "https://test.pypi.org/project/data-ecosystem-services"
"Documentation" = "https://gift.readthedocs.io"
"Repository" = "https://github.com/cdcent/data-ecosystem-services"

[tool.poetry]
name = "data_ecosystem_flask"
version="202307.0.13"
description = "Program Agnostic Data Ecosystem (PADE) - Flask Web Service"
authors = ["John Bowyer <zfi4@cdc.gov>"]
license = "Apache"
homepage="https://test.pypi.org/project/data-ecosystem-services"
repository="https://github.com/cdcent/data-ecosystem-services"
classifiers=[
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.9"
]
include = [ "readme.md",
            "license.md",
            "setup.cfg",
            "setup.py",
            "pyproject.toml",
            "data_ecosystem_flask/data_ecosystem_flask/**/*.py",
            "data_ecosystem_flask/**/*.py",
            "ocio/**/*.json",            
            "dev_schema/**/*.xlsx",     
            "dev_schema/**/*.json",
            "ocio/ocio_pade_dev/config/config.dev.json"    
        ]

[tool.poetry.dependencies]
python = "^3.9"
flask = "^2.0.0"
numpy = "^1.23.0"
wrapt = "^1.14.0"
six = "^1.16.0"
openpyxl = "^3.1.2"
oauthlib = "^3.2.2"
xlsxwriter = "^3.1.0"
werkzeug = "^2.3.3"
flask-restx = "^1.1.0"
flake8 = "^4.0.1"
pycodestyle = ">=2.8.0,<2.9.0"
rsconnect-python = "^1.17.1"
requests = "^2.31.0"
setuptools = "65.6.3"
alation = "^0.1.14"
opentelemetry-sdk = "^1.17.0"
azure-monitor-opentelemetry-exporter = {version = "^1.0.0b14", allow-prereleases = true}
opentelemetry-instrumentation-flask = "^0.39b0"
python-dotenv = "^1.0.0"
rsconnect = "^0.1.3"
flask-restful = "^0.3.10"
data-ecosystem-services = "^202307.0.12"



[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
flaskapp = "data_ecosystem_flask.app:app"


[tool.pytest.ini_options]
minversion="6.0"
addopts="-ra -q --cov --cov-report html --cov-report term-missing --cov-fail-under 15"
testpaths=[
    "data_ecosystem_services/tests"
]

[tool.mypy]
warn_unused_configs=true
namespace_packages=true
explicit_package_bases=true
ignore_missing_imports=true
exclude='tests'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
