[tool.poetry]
name = "traceloop-sdk"
version = "0.0.2"
description = ""
authors = ["Gal Kleinman <gal@traceloop.com>", "Nir Gazit <nir@traceloop.com>", "Tomer Friedman <tomer@traceloop.com>"]
readme = "README.md"
packages = [{include = "traceloop"}]

[tool.poetry.dependencies]
python = "^3.9"
opentelemetry-sdk = "1.18.0"
opentelemetry-api = "1.18.0"
opentelemetry-exporter-otlp-proto-http = "1.18.0"
opentelemetry-instrument-openai = "0.6.0"
openai = "^0.27.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

